#!/bin/zsh
echo Installing root certificate...
keytool -import -trustcacerts -alias odcbelastingdienstg1rootca -file /Users/Groea10/Downloads/odcbelastingdienstg1rootca.crt -cacerts -storepass changeit
#-keystore ${JAVA_HOME}/lib/security/cacerts

echo Installing develop environment certificate...
keytool -import -trustcacerts -alias wildcard.belastingdienst.nl -file /Users/Groea10/Downloads/wildcard.belastingdienst.nl.cer -cacerts -storepass changeit

echo Installing develop repository certificate...
keytool -import -trustcacerts -alias poosnxsl10.ont.belastingdienst.nl -file /Users/Groea10/Downloads/poosnxsl10.ont.belastingdienst.nl.cer -cacerts -storepass changeit

echo Finished...
